[project]
name = "ppsn-experiment"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
  "ariel",
  "mujoco>=3.3.6",
  "nevergrad>=1.0.12",
  "networkx>=3.2.1",
  "numpy>=2.0.2",
  "rich>=14.1.0",
  "torch>=2.8.0",
  "typer>=0.15.0",
]

[tool.uv]
package = false

[tool.uv.sources]
ariel = { path = "ariel", editable = true }
